# Generated by Django 4.1 on 2022-09-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0002_blogmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
